[package]
name = "nouns_client_proof"
type = "bin"
authors = ["AZKR Team"]
compiler_version = "0.5.1"

[dependencies]
trie = { git = "https://github.com/aragonzkresearch/noir-trie-proofs", tag = "main", directory = "lib" }
