[package]
name = "nouns_hash_proof"
type = "bin"
authors = [""]
compiler_version = "0.7.1"

[dependencies]
trie = { git = "https://github.com/aragonzkresearch/noir-trie-proofs", tag = "main", directory = "lib" }
