[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc-version = "0.8.17"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }